/**
 * 推しカレ
 * 推しカレのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sample@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Signup model module.
 * @module model/Signup
 * @version 1.0.0
 */
class Signup {
    /**
     * Constructs a new <code>Signup</code>.
     * Serializer for the signup view.
     * @alias module:model/Signup
     * @param id {Number} 
     * @param username {String} この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。
     * @param password {String} 
     */
    constructor(id, username, password) { 
        
        Signup.initialize(this, id, username, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, username, password) { 
        obj['id'] = id;
        obj['username'] = username;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>Signup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Signup} obj Optional instance to populate.
     * @return {module:model/Signup} The populated <code>Signup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Signup();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('change_password')) {
                obj['change_password'] = ApiClient.convertToType(data['change_password'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Signup</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Signup</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Signup.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }

        return true;
    }


}

Signup.RequiredProperties = ["id", "username", "password"];

/**
 * @member {Number} id
 */
Signup.prototype['id'] = undefined;

/**
 * この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。
 * @member {String} username
 */
Signup.prototype['username'] = undefined;

/**
 * @member {String} email
 */
Signup.prototype['email'] = undefined;

/**
 * @member {String} password
 */
Signup.prototype['password'] = undefined;

/**
 * @member {Boolean} change_password
 * @default false
 */
Signup.prototype['change_password'] = false;






export default Signup;

