/**
 * 推しカレ
 * 推しカレのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sample@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TokenObtainPair model module.
 * @module model/TokenObtainPair
 * @version 1.0.0
 */
class TokenObtainPair {
    /**
     * Constructs a new <code>TokenObtainPair</code>.
     * @alias module:model/TokenObtainPair
     * @param username {String} 
     * @param password {String} 
     * @param access {String} 
     * @param refresh {String} 
     */
    constructor(username, password, access, refresh) { 
        
        TokenObtainPair.initialize(this, username, password, access, refresh);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, password, access, refresh) { 
        obj['username'] = username;
        obj['password'] = password;
        obj['access'] = access;
        obj['refresh'] = refresh;
    }

    /**
     * Constructs a <code>TokenObtainPair</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TokenObtainPair} obj Optional instance to populate.
     * @return {module:model/TokenObtainPair} The populated <code>TokenObtainPair</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenObtainPair();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('access')) {
                obj['access'] = ApiClient.convertToType(data['access'], 'String');
            }
            if (data.hasOwnProperty('refresh')) {
                obj['refresh'] = ApiClient.convertToType(data['refresh'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TokenObtainPair</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TokenObtainPair</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TokenObtainPair.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['access'] && !(typeof data['access'] === 'string' || data['access'] instanceof String)) {
            throw new Error("Expected the field `access` to be a primitive type in the JSON string but got " + data['access']);
        }
        // ensure the json data is a string
        if (data['refresh'] && !(typeof data['refresh'] === 'string' || data['refresh'] instanceof String)) {
            throw new Error("Expected the field `refresh` to be a primitive type in the JSON string but got " + data['refresh']);
        }

        return true;
    }


}

TokenObtainPair.RequiredProperties = ["username", "password", "access", "refresh"];

/**
 * @member {String} username
 */
TokenObtainPair.prototype['username'] = undefined;

/**
 * @member {String} password
 */
TokenObtainPair.prototype['password'] = undefined;

/**
 * @member {String} access
 */
TokenObtainPair.prototype['access'] = undefined;

/**
 * @member {String} refresh
 */
TokenObtainPair.prototype['refresh'] = undefined;






export default TokenObtainPair;

