# Generated by Django 4.2.9 on 2024-01-13 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("app", "0001_initial"),
        ("app", "0002_alter_event_date_alter_event_description_and_more"),
        ("app", "0003_remove_artist_owner_alter_event_artist_and_more"),
        ("app", "0004_alter_event_artist_alter_event_owner"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="アーティスト名を入力してください。",
                        max_length=200,
                        verbose_name="Artist Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="アーティストの説明を入力してください。",
                        null=True,
                        verbose_name="Artist Description",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="イベント名を入力してください。",
                        max_length=200,
                        verbose_name="Event Name",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        help_text="イベントの日時を入力してください。", verbose_name="Event Date"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="イベントの場所を入力してください。",
                        max_length=200,
                        null=True,
                        verbose_name="Event Location",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="イベントの説明を入力してください。",
                        null=True,
                        verbose_name="Event Description",
                    ),
                ),
                (
                    "public",
                    models.IntegerField(
                        default=0,
                        help_text="公開設定を入力してください。0:非公開, 1:公開。",
                        verbose_name="Public Setting",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_events",
                        to="app.artist",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
