/**
 * 推しカレ
 * 推しカレのAPI
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sample@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.ArtistsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ArtistsApi', function() {
    describe('artistsCreate', function() {
      it('should call artistsCreate successfully', function(done) {
        //uncomment below and update the code to test artistsCreate
        //instance.artistsCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('artistsDestroy', function() {
      it('should call artistsDestroy successfully', function(done) {
        //uncomment below and update the code to test artistsDestroy
        //instance.artistsDestroy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('artistsList', function() {
      it('should call artistsList successfully', function(done) {
        //uncomment below and update the code to test artistsList
        //instance.artistsList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('artistsPartialUpdate', function() {
      it('should call artistsPartialUpdate successfully', function(done) {
        //uncomment below and update the code to test artistsPartialUpdate
        //instance.artistsPartialUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('artistsRetrieve', function() {
      it('should call artistsRetrieve successfully', function(done) {
        //uncomment below and update the code to test artistsRetrieve
        //instance.artistsRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('artistsUpdate', function() {
      it('should call artistsUpdate successfully', function(done) {
        //uncomment below and update the code to test artistsUpdate
        //instance.artistsUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
